# Main mpv options
background-color='#1e1e2e'
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'

osd-font=JetBrainsMono Nerd Font
profile=high-quality
# hwdec=auto-safe
vo=gpu-next
hwdec=vulkan
gpu-api=vulkan
gpu-context=waylandvk
interpolation=yes #Smooth 120Hz experience. 
audio-spdif=ac3,dts,dts-hd,truehd # eac3
# audio-channels=stereo,5.1,7.1 
# loop-playlist=inf
loop-file=inf
mute=no
volume=100
volume-max=100
video-zoom=0
save-position-on-quit=yes
watch-later-options=start
# watch-later-options-add=
# watch-later-options-remove=volume
# watch-later-options-remove=mute
# watch-later-options-remove=video-zoom
sub-file-paths=sub:subtitles:Subs
slang=pl,pl_PL,pl-PL,en,eng,en_US,en-US
sid=auto
sub-auto=fuzzy
# alang=jp,jpn,japanese,en,eng,english

# Stats script options
# Options are on separate lines for clarity
# Colors are in #BBGGRR format
script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=d5e294
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=d5e294

# External script options
# It is fine to leave these here even if one does not use these scripts because they are just ignored unless a script uses them

# UOSC options
script-opts-append=uosc-color=foreground=94e2d5,foreground_text=313244,background=1e1e2e,background_text=cdd6f4,curtain=181825,success=a6e3a1,error=f38ba8

# required so that the 2 UIs don't fight each other
osc=no

# uosc provides seeking & volume indicators (via flash-timeline and flash-volume commands)
# if you decide to use them, you don't need osd-bar
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=yes

video-sync=display-resample
