general {
  hide_cursor = true
  ignore_empty_input = true
  fractional_scaling = 2
}

auth {
	pam:enabled = true
	pam:module = hyprlock
	fingerprint:enabled = true
	fingerprint:retry_delay = 1000
	fingerprint:ready_message = (Scan fingerprint to unlock)
	fingerprint:present_message = Scanning fingerprint
}

background {
  monitor = 
  path = screenshot
#  color = rgba(17, 17, 27, 1.0)
  color = rgba(0, 0, 0, 1.0)
  blur_size = 3
  blur_passes = 3
  noise = 0.011700
  contrast = 1.0
  brightness = 0.6
#  vibrancy = 0.5
  vibrancy_darkness = 0.1
}

input-field {
  monitor =
  size = 12%, 5%
  outline_thickness = -1
  dots_size = 0.330000
  dots_spacing = 0.300000
  dots_center = true
  dots_rounding = 10
  outer_color = rgba(24, 24, 37, 0)
  inner_color = rgba(30, 30, 46, 0.0)
  font_color = rgba(205, 214, 244, 0.75)
  fade_on_empty = true
  fade_timeout = 1500
  placeholder_text =
  hide_input = false
  rounding = 12
  shadow_passes = 0
  shadow_size = 3
  shadow_color = rgba(30, 32, 48, 0.1)
  shadow_boost = 1.200000
  check_color = rgb(166, 227, 161)
  fail_color = rgb(243, 139, 168)
  fail_text = wrong password
  font_family = JetBrainsMono Nerd Font
  capslock_color = -1
  numlock_color = -1
  bothlock_color = -1
  invert_numlock = false
  swap_font_color = false

  position = 0, -50
  halign = center
  valign = center
}


label {
  monitor = 
#  text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
  text = $TIME
  text_align = 
  color = rgba(205, 214, 244, 0.75)
  font_size = 250
  font_family = WDXL Lubrifont TC
  rotate = 0.000000
  shadow_passes = 0
  shadow_size = 1
  shadow_color = rgba(30, 32, 48, 0.1)
  shadow_boost = 1.200000

  position = 0, 210
  halign = center
  valign = center
}

label {
  monitor =
  text = $FPRINTPROMPT
  color = rgba(205, 214, 244, 0.6)
  font_size = 24
  font_family = JetBrainsMono Nerd Font
  shadow_passes = 0
  shadow_size = 1
  shadow_color = rgba(30, 32, 48, 0.1)
  shadow_boost = 1.200000

  position = 0, 25
  halign = center
  valign = center
}
