general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = niri msg output eDP-1 on  # to avoid having to press a key twice to turn on the display.
	inhibit_sleep = 3
}

listener {
	timeout = 30
	on-timeout = notify-send -u low 'System is idle'
	on-resume = notify-send -u low 'System is no longer idle'
}

# Dim the screen
listener {
    timeout = 120                                # 2 min.
    on-timeout = brightnessctl -s set 10         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

# Turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
listener { 
    timeout = 120                                                 # 2 min
    on-timeout = brightnessctl -sd chromeos::kbd_backlight set 0  # turn off keyboard backlight.
    on-resume = brightnessctl -rd chromeos::kbd_backlight         # turn on keyboard backlight.
}

# Lock the screen
listener {
    timeout = 180                                 # 3 min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
	on-resume = brightnessctl -r
}

# Turn off screen
listener {
    timeout = 210                                                     # 3.5 min
    on-timeout = niri msg output eDP-1 off                            # screen off when timeout has passed
    on-resume = niri msg output eDP-1 on                              # screen on when activity is detected after timeout has fired.
}

# Suspend the system
listener {
    timeout = 600                                # 10 min
    on-timeout = systemctl suspend               # suspend pc
	on-resume = nmcli device wifi rescan
}
